### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by SchmittAntonin** [ugumba/homey-panasonic-comfort-cloud-alt#11]
Hi,

Trying for the 1st time to play with unofficial App for Homey and I have the following message when I try to install the PCC Alt App:
✓ Pre-processing app...
Added FlowCard `change-air-swing-leftright` for type `actions`
Added FlowCard `change-air-swing-updown` for type `actions`
Added FlowCard `change-eco-mode` for type `actions`
Added FlowCard `change-fan-speed` for type `actions`
Added FlowCard `change-operation-mode` for type `actions`
Added Driver `aircon`
Added Capability `air_swing_lr`
Added Capability `air_swing_ud`
Added Capability `eco_mode`
Added Capability `fan_auto_mode`
Added Capability `fan_speed`
Added Capability `nanoe_mode`
Added Capability `operation_mode`
✓ Typescript detected. Compiling...
✖ Error occurred during while running tsc
error TS2688: Cannot find type definition file for 'homey'.
  The file is in the program because:
    Entry point for implicit type library 'homey'

✖ Error: Typescript compilation failed.
    at App.transpileToTypescript (/usr/local/lib/node_modules/homey/lib/App.js:91:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.preprocess (/usr/local/lib/node_modules/homey/lib/App.js:833:7)
    at async App.install (/usr/local/lib/node_modules/homey/lib/App.js:767:7)
    at async exports.handler (/usr/local/lib/node_modules/homey/bin/cmds/app/install.js:25:5)

Would it be possible to give me a hint on this message and how to solve it?

Many thanks !

**Comment by ugumba** [comment]
Are you on MacOS or Windows?  I've only been using Windows, but recall another user had issues on Mac:
https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906/53

**Comment by SchmittAntonin** [comment]
Many thanks for your quick feedback. Indeed, I’m on Mac. I’ll have to find
a PC to try to install it then.

Best regards,

Antonin


Le lun. 11 mars 2024 à 10:51, Robert Schmidt ***@***.***> a
écrit :

**Comment by ugumba** [comment]
Cool - let me know how it goes.
I'll check with the forum if anyone else have installed it successfully from Mac.  It might just be a config issue.

**Comment by Magnusri** [comment]
I suspect you may be in a non typescript project trying to run a typescript file. Try the things from "Converting an existing app to TypeScript" here: https://apps.developer.homey.app:8443/guides/tools/typescript

You may even just be missing the "homey app add-types" command

**Comment by SchmittAntonin** [comment]
Hi @Magnusri ,
Your were right. The "homey app add-types" helped to solve the problem. I had to run all the lines in sudo (probably because my computer is not properly set), but everything works fine now.
Thank you bot @ugumba  and @Magnusri for your help.
