### ISSUE TITLE
Failed authentification

### ISSUE THREAD

**Issue by AntoninSchmitt** [ugumba/homey-panasonic-comfort-cloud-alt#13]
Dear @ugumba,
I finally succeeded in installing the Panasonic Alt app on my Homey pro and it worked perfectly fine for several days.
Unfortunately, since march, 18th 00:00, I’ve lost the connection with Panasonic. I needed few days to discover the bug. It seems that my credentials aren’t recognized anymore (despite working fine before and meanwhile without any issue on the official Idevice app.
FYI, as I was unable to understand how to create new users on the Panasonic app, I’ve added my admin credentials in Homey.
The error message is « request failed with error code 401 ».
Am I the only one to experience such issue ?
Many thanks for your help.

**Comment by ugumba** [comment]
No, this has affected everyone.
I hadn't gotten around to ensuring an issue was registered here, so thanks.
See discussion here: https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906

**Comment by nickmurison** [comment]
This _should_ fix the issue: https://github.com/ugumba/homey-panasonic-comfort-cloud-alt/pull/14, but it only addresses that Panasonic's servers want the app to send a newer version number. 

It doesn't address the MFA challenge, but as far as I can tell Panasonic's authentication flow doesn't require a MFA challenge if you've already used the credentials in the official Comfort Cloud app.

**Comment by ugumba** [comment]
Thanks, @nickmurison, for diving into this!  I personally jumped to conclusions, and really appreciate that there was an easy fix.
