### ISSUE TITLE
"always on" option

### ISSUE THREAD

**Issue by ugumba** [ugumba/homey-panasonic-comfort-cloud-alt#16]
Would be nice to prevent device from being turned off from the Homey app, since it is too easy to click the icon by mistake. 

https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906/134

**Comment by jarll** [comment]
I have a patch in my fork (based on v1.1.11) that works from a functional point of view, but it's not "perfect". I basically block sending Power.Off to the device if a setting alwaysOn is true. The icon of the device will blur, indicating device is off, but it's not. On next sync from device (60sec later), Homey will figure out that device is actually on, and unblur the icon.
I haven't been able to figure out how to prevent Power.Off beeing triggered in the first place from UI.

**Comment by ugumba** [comment]
That sounds good enough to satisfy the original request!
