### ISSUE TITLE
Expose outside temperature in Homey

### ISSUE THREAD

**Issue by ugumba** [ugumba/homey-panasonic-comfort-cloud-alt#21]
https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906/170?u=robert_schmidt

**Comment by Magnusri** [comment]
This can probably be closed now :)

**Comment by ugumba** [comment]
Yep :-) Implemented by https://github.com/ugumba/homey-panasonic-comfort-cloud-alt/pull/28
