### ISSUE TITLE
Current power & outside temperature

### ISSUE THREAD

**Issue by MathiasSvDK** [ugumba/homey-panasonic-comfort-cloud-alt#25]
Would be sick to be able to get the outside temperature as someone else requested but also the current power draw.
Both are possible in homeassistant, so i think it should be douable?

**Comment by ugumba** [comment]
Agreed.  Outside temperature is readily available from the client API, so that should be easy.
The _current_ power draw is _not_ available.  

However, the API does provide historical power draw, at the granularity of full hours - it's the same information that you can see under Statistics in the official mobile app.  I guess the total draw (kWh) from the last full hour could be presented as a "faux" current power draw (kW), but I'm not comfortable about it - people are bound to have flows run actions based on these values.

**Comment by Magnusri** [comment]
I have these things, outside temp and the power history for statistics only, in my fork (Which is no longer working because i didnt maintain it properly..) I will rewrite those parts, and submit a proper pull request for these to your project, ugumba.

**Comment by MathiasSvDK** [comment]
That would be sick Magnus!
I also want the power just for statistics only.

ons. 27. nov. 2024 kl. 09.49 skrev Magnusri ***@***.***>:

**Comment by Magnusri** [comment]
Hello again

The power consumption from the API comes in the form of "per hour", with the current hour being an "up to right now -number". This means that the best we can do is a "previous hour as current hour" delay. As in, we get the previous complete hour, and register it as the current hourly consumption in the Homey Device which results in an hour delay in power report shown as current draw.

It will work over time, but all power consumption will be offset by one hour in the logs.

What do you think, @ugumba? I have it ready for a PR now.

**Comment by Magnusri** [comment]
As ugumba stated above, it could pose a problem if people doesn't know this and use the consumption for a flow condition..

**Comment by MathiasSvDK** [comment]
How come it should be an hour delayed? 
In homeassistant it's not an hour delayed. Maybe its possible to look into the homeassistant module and see how they did it?

**Comment by Magnusri** [comment]
That was interesting!

They have made a diff function that calculates the consumption based on the current unfinished hour by checking it every minute and taking the difference each minute * 60 as the current consumption per hour. That would be a lot more accurate.

I will implement it tomorrow if i get the time!

Thank you for the information.

**Comment by MathiasSvDK** [comment]
Sick! Excited to have it!

**Comment by ugumba** [comment]
> What do you think, @ugumba? I have it ready for a PR now.

The method from HA sounds like the way to go, theoretically!  
I wasn't even aware that "live" consumption from the current hour is available.

It doesn't seem like the current hour consumption returned from the API updates very often though.  From my (very short) experimentation, it seems to change only every 15 minutes or so.  So calling the API every 60s is definitely overkill (risking throttling measures from Panasonic), and will give you a difference of 0kWh most minutes.

**Comment by Magnusri** [comment]
Had a look around as well. Seeing the same results as you in regards to the updates of the current hour consumption. This means that the homeassistant version is better to some degree, but would probably still not be good enough in terms of someone using the values for a flow condition..

I also noted that the Homeassistant version gets device data every 30 seconds, and consumption data every 60 seconds by default. (Configurable by end user)


By the way; I am having difficulties adding the default "measure_power" capability to the device using the homey CLI. Have you done anything special in regards to capabilities? If i add it using the CLI, it removes all your custom ones... If i add it to the app.json manually, it doesn't seem to do anything at all.

**Comment by Magnusri** [comment]
I propose keeping the hourly check, as it is more stable and correct. Since it is a confirmed value from Panasonic instead of trying to calculate it ourselves.

To remedy any confusion, I can rename the consumption value to something like "Hourly avg consumption" to tell users that it is not an exact or current value. This title will show when trying to add it as a flow condition.

Nevermind what i said above about the "measure_power" capability.. I was doing something wierd. Works now

**Comment by MathiasSvDK** [comment]
The value from panasonic is anyways also just a estimation as they also
mention in the app

**Comment by ugumba** [comment]
I agree - using the plain value from the API is clean and pragmatic.

To be picky, the term "hourly avg consumption" is a bit unclear - is it the average kWh (consumption) over several hours, or the average W (power) over the last whole hour?

First, how about exposing the consumption from the last whole hour (directly from the API) as "last hour consumption" (unit Wh or kWh - I don't know what the Homey SDK prefers)?
This, at least, is a value which can be depended on - even if it is updated only once an hour.

Second, I'm open to exposing an experimental power estimate as a second property.
I'm not convinced about its usefulness, given that the current hour's consumption updates only every 15 minutes.

________________________________

**Comment by Magnusri** [comment]
I have made it a separate value now using the avg W consumption during the last whole hour (directly from the API), as well as added the outside temperature. I will test it today, adjust if needed, and post a pull request when i think it is OK.

Homey likes power values being represented as current W draw. Which is the same as the kWh that is sent from the Panasonic API  when represented as whole hours.

Will look into adding the homeassistant way as another separate value as well. (Maybe I could add some "experimental" toggle in the settings to enable/show it?)

**Comment by MathiasSvDK** [comment]
[image: Screenshot 2024-11-29 at 13.39.28.png]
Here you go

**Comment by MathiasSvDK** [comment]
Didnt work i see. 
Here you do
![Screenshot 2024-11-29 at 13 39 28](https://github.com/user-attachments/assets/d0cc8c41-141a-473a-890e-ddf83920f18a)

**Comment by Magnusri** [comment]
> How is it looking @Magnusri ?

Just made a PR for the hourly avg fetching + outside temperature now. I was getting some wierd numbers trying to implement the solution for the best effort (15 mins) fetching used in the homeassistant version... I will look into it again sometime this week i think. Would be cool to have a better estimate (if we can make it work). I might push my early tests of it more often to my fork while looking at it next time.
