### ISSUE TITLE
Multiple authentication flows initiated for multiple devices?

### ISSUE THREAD

**Issue by ugumba** [ugumba/homey-panasonic-comfort-cloud-alt#26]
https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906/186?u=robert_schmidt

This could be explained if Homey initializes devices in parallel.

The solution would be to wrap the first if-statement in MyDriver.getClient() with a repeated if and mutex.

**Comment by jarll** [comment]
Testet in my env with 4 devices: I now see only one authentication (as expected) and communication with all 4 devices (set temp, get capabilities) works as expected. Verified both with my devices at home and using the Panasonic Android APP.
QA OK. Ready for merge.
